### ISSUE TITLE
[São Paulo, SP] Engenheiro de Software Senior na sim;paul

### ISSUE THREAD

**Issue by jjaviles2010** [flutterbr/vagas#10]
## Descrição da vaga

Desenvolver aplicativos para Android e IOS com Flutter.
Realizar análise e dar sugestões técnicas para implementação de novas funcionalidades.
Contribuir em decisões de arquitetura.
Implementar protótipos do time de UX, com atenção aos detalhes visuais e compatibilidade entre devices.
Realizar integração do aplicativo com as APIs RESTful.
Realizar processo de deploy para as lojas(App Stores e Google Play Store).

## Local

Escritório São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- Vale Transporte
- Vale Refeição
- Vale Alimentação

## Requisitos

Ter pelo menos 4 anos de experiência.
Ter experiência com desenvolvimento Mobile em linguagem nativa ou híbrida (ionic, react native).
Conhecimento profundo de lógica de programação e orientação a objetos.
Conhecimento de Flutter.
Conhecimento em algumas das seguintes linguagens de programação (Dart, Java, C#, Kotlin, Swift).
Ter facilidade para trabalhar em equipe.
Conhecimento de Git e GitFlow.
Conhecimento de SQL.
Familiaridade com processo de desenvolvimento de software ágil (como XP, Scrum e Kanban).
Boas práticas de desenvolvimento.
Experiência em mobile integrando com serviços RESTful.
Conhecimentos Testes Unitários.
Conhecimento de alguma arquitetura (MVVM, MVP, BLoC).
Conhecimento em design patterns e SOLID

## Contratação

CLT a combinar

## Nossa empresa

A sim;paul é uma fintech brasileira que está redesenhando a maneira como o mercado financeiro se relaciona com o cliente. Com uma tecnologia que já nasce no modelo “open banking”, a sim;paul leva transparência, simplicidade e liberdade a um mercado acostumado a esconder o jogo. Simples assim.

## Como se candidatar

Por favor envie um email para sabrina.vasconcellos@simpaul.com.br com seu CV anexado - enviar no assunto: Vaga Flutter

## Labels

- CLT
- Sênior
- Mobile
- Flutter

**Comment by BarrosLucas** [comment]
Há disponibilidade para trabalho remoto?
