### ISSUE TITLE
[Curitiba] Lead Software Engineer (Flutter) na Noodle

### ISSUE THREAD

**Issue by Janaina-Lima** [flutterbr/vagas#107]
A Noodle é uma Fintech voltada para artistas, músicos e gravadoras que buscam financiamento e recursos para estas áreas.

https://www.noodle.cx/

Responsabilidades

Liderar equipe de desenvolvimento, garantindo a qualidade das entregas.
Desenvolver e avaliar soluções de desenvolvimento de sistemas.
Analisar as soluções e propor desenvolvimento de sistemas orientado ao negócio.
Gerenciar recursos e atuar em melhorias de sistemas e realizar a gestão dos projetos.
Validar a implantação de sistemas de software.
Requisitos

Formação da área de Engenharia de Software, Computação, Bacharelado em Informática, engenharia da Computação e áreas afins.
Experiência mínima de 4 anos com desenvolvimento de sistemas.
Experiência de 3 anos com Flutter.
Conhecimento em Google Cloud
Experiência com gestão de equipes
Experiência com APIs (core banking, câmbio, risco, cartão)

Diferencial: 

Conhecimento em metodologias ágeis.
Experiência em Fintech.

Perfil:

Empreendedor
Movido a entregas
Agilidade e proatividade
Comunicação clara e objetiva
Modelo de Contratação:

100% remoto
Contrato PJ
Participação nos resultados

Por favor envie um email para contato@icontalent.com.br com seu CV anexado - enviar no assunto: Vaga Lead Software Engineer

## Labels
- PJ
- Sênior

**Comment by jeaanlucas** [comment]
Esses 3 anos com Flutter são obrigatórios?
A linguagem entrou em stable release em 04/12/2018.

**Comment by cezar-pereira** [comment]
> Esses 3 anos com Flutter são obrigatórios?
> A linguagem entrou em stable release em 04/12/2018.

Ainda bem que pediram apenas 3 anos e não "dez". E nem precisa ter nobel da paz...

**Comment by Janaina-Lima** [comment]
preferencialmente 3 anos de experiência :) - o profissional será líder do time de mobile.

**Comment by klausgreiner** [comment]
Você limita sua vaga a somente que entrou no lançamento do flutter antes da release. Seria mais razoável pedir 4 anos em experiência mobile qualquer linguagem e +1 ano em flutter. Acredito que em flutter quem tem muita experiência deve ter 2,5 anos e 90% das pessoas que entraram cedo tem 2 anos de flutter.

**Comment by Janaina-Lima** [comment]
vaga encerrada com sucesso!
