### ISSUE TITLE
[Remoto] Flutter Developer na ioasys

### ISSUE THREAD

**Issue by toshiossada** [flutterbr/vagas#109]
## Descrição da vaga

A ioasys é especialista em criar soluções únicas para empresas ousadas. Somos experts em trazer o melhor do universo digital para nossos clientes e a transformar a sociedade, a repensá-la e a evoluí-la. Ajudamos marcas a inovar através da transformação digital e seguindo os princípios de metodologia ágil e abordagem centrada ao usuário, modificando a realidade das pessoas com tecnologia e inovação de ponta a ponta. Não somos apenas pensadores, somos realizadores! Estamos projetando um mundo mais acessível, conectado e intuitivo, como deveria ser.

Buscamos um time diverso, livre de preconceitos e aberto a todos os tipos de raças, cores, corpos e crenças. Nosso propósito estampado em nossas camisetas atuais "De Pessoas. Para Pessoas." traduz a importância de um ambiente heterogêneo, repleto de vivências e impressões da sociedade e suas necessidades.

Propiciamos um ambiente inovador dedicado ao crescimento, com profissionais incríveis e de aprendizado constante em escritórios que estimulam a criatividade e produtividade. Além do nosso horário ser flexível (trabalhamos de segunda a sexta), acreditamos na oportunidade de estarmos todos criando uma empresa que desenvolve soluções que afetam positivamente a vida de milhões de pessoas em diversos segmentos. Você estará em uma equipe horizontal e transparente, que não apenas valoriza suas ideias, mas também espera que você faça parte da construção da empresa com a gente.

Para a vaga de Pessoa Desenvolvedora Flutter, buscamos um profissional que desenvolva aplicações e funcionalidades com Dart e Flutter, mantendo o código de forma clara e limpa, levando em conta boas práticas de desenvolvimento. É interessante que este profissional tenha conhecimento dos conceitos e boas práticas da tecnologia e sua interação com as plataformas nativas. Também buscamos um profissional que trabalhe utilizando algum padrão ou ferramenta para gerenciamento de estado, como por exemplo Bloc e MobX, ou padrões como o MVVM. Este profissional irá desenvolver APPs com Flutter para grandes empresas do mercado nacional e internacional.

## Local

Remoto

## Benefícios

Regime CLT ou PJ;
Liberdade para exercer suas habilidades em um ambiente dinâmico e horizontal;
Jornada flexível;
Day Off – Birthday;
Acesso a plataformas de cursos online;
Parceria com Universidades;
Talks e Cursos internos ministrados por nossos especialistas;
Curso de Inglês (In Company).

## Requisitos

Domínio do Dart/Flutter e seus conceitos
Experiência com integrações REST e SOAP;
Conhecer algum gerenciamento de estado (Bloc, MobX, Redux etc. )
Conhecimento das guidelines de UI de ambas plataformas mobile (MaterialApp, CupertinoApp)
Versionamento de código Git;
Metodologias ágeis (Scrum);

**Desejáveis:**
Padrão MVVM;
Conhecimento ou experiência com plataformas nativas;
Integração do Flutter em projetos Android e/ou IOS existentes
Integração com código nativo utilizando MethodChannel
Ter experiência em processos de code review;
Ter conhecimento em testes unitários e de interface;
Teste unitários com Mockito e Flutter Test.

## Contratação

PJ ou CLT a combinar

## Nossa empresa

Somos especialistas em criar soluções únicas para empresas ousadas. Digitalmente, mas sempre com alma. Para nós, inovação, design e tecnologia são apenas meios que utilizamos para trazer o melhor do universo digital para nossos clientes e alcançar soluções que irão transformar a sociedade.

Nascemos em Minas Gerais, expandimos nossas operações pelo Brasil e atualmente temos o orgulho de ver nossos projetos percorrendo o mundo todo. Somos formados por um time diverso e múltiplo que acredita na essência de que as nossas entregas são sempre feitas de pessoas e projetadas para pessoas.

Transformamos a sociedade junto de algumas das maiores empresas do mercado nacional e internacional, como: Banco Inter, Burger King, BASF, VR Benefícios, LATAM Airlines, Pfizer, Localiza, Fleury, DMCard, Fundação Dom Cabral e Suvinil. 

Não somos apenas pensadores, somos realizadores. Investimos incansavelmente a nossa energia na busca de soluções inovadoras com objetivo de reinventar experiências que tenham sempre alto impacto aos usuários, seguindo os princípios de metodologia ágil e design centrado no usuário. Acreditamos extremamente no que criamos na ioasys e temos a certeza de que temos o poder de impactar positivamente milhões de vidas com cada projeto que executamos.

Queremos colaborar com a sociedade construindo um legado de um mundo acessível, conectado e intuitivo. Como deveria ser.

## Como se candidatar

Pra toda a comunidade de Flutter temos vagas abertas em todos os níveis.
Quem quiser conhecer e saber um pouco mais sobre nós pode entrar em contato comigo e se candidatem.
https://www.linkedin.com/in/toshiossada/

https://ioasys.gupy.io/jobs/920840?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

## Labels

- Home Office
- Remoto
- CLT
- PJ
- Junior
- Pleno
- Sênior

**Comment by docputs** [comment]
A vaga ainda está aberta?
