### ISSUE TITLE
[Cidade] Flutter Developer na NOME DA EMPRESA

### ISSUE THREAD

**Issue by AndreNuernberg** [flutterbr/vagas#114]
## Descrição da vaga

Projeto mobile bazinga em Flutter, etc.

## Local

Remoto ou Escritório, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Flutter
- 2 anos de experiência com desenvolvimento mobile nativo

**Desejáveis:**
- conhecimentos em react native
- conhecimentos em ionic

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga Flutter

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

## Labels

- Alocado
- CLT
- Estágio
- Freela
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by AndreNuernberg** [comment]
> ## Descrição da vaga
> Projeto mobile bazinga em Flutter, etc.
> 
> ## Local
> Remoto ou Escritório, São Paulo - Vila Olímpia
> 
> ## Benefícios
> * Plano de saúde
> * Seguro de vida
> * VR de R$ X/dia
> * Auxílio creche
> * ...
> 
> #### Diferenciais
> * 2 horas de almoço
> * monte a sua máquina como desejar
> * frigobar sempre cheio :P
> * sala de jogos
> * ...
> 
> ## Requisitos
> **Obrigatórios:**
> 
> * 3 anos de experiência com Flutter
> * 2 anos de experiência com desenvolvimento mobile nativo
> 
> **Desejáveis:**
> 
> * conhecimentos em react native
> * conhecimentos em ionic
> 
> **Diferenciais:**
> 
> * projetos opensource
> 
> ## Contratação
> PJ a combinar
> 
> ## Nossa empresa
> Aqui na Corporação ACME somos líderes em...
> 
> ## Como se candidatar
> Por favor envie um email para [email@email.com.br](mailto:email@email.com.br) com seu CV anexado - enviar no assunto: Vaga Flutter
> 
> ## Tempo médio de feedbacks
> Costumamos enviar feedbacks em até XX dias após cada processo.
> E-mail para contato em caso de não haver resposta: [feedbacks@empresasuperlegal.com.br](mailto:feedbacks@empresasuperlegal.com.br)
> 
> ## Labels
> * Alocado
> * CLT
> * Estágio
> * Freela
> * Júnior
> * PJ
> * Pleno
> * Remoto
> * Sênior

**Comment by thassio-vinicius** [comment]
ué

**Comment by AndreNuernberg** [comment]
> ué

Mil desculpas, criei sem querer, como que eu deleto?
