### ISSUE TITLE
[Remoto] Flutter Software Engineer no iFood

### ISSUE THREAD

**Issue by glaydsonarantesp** [flutterbr/vagas#125]
## Descrição da vaga

- Collaborate in the definition of concepts such as project-wide coding style guides
- Build quick prototypes to prove concepts
- Enforce quality during code review and maintenance practices
- Debug performance issues in apps and bottlenecks in CI lanes
- Integrate with third party APIs
- Efficiently scale components through tuning and / or major refactorings
- Conceptualize and develop components for a monorepo mobile app

## Local

Remoto, Escritórios (há definir data de abertura) ou CoWorkings

## Benefícios & Diferenciais

Veja [em nosso site de Carreiras](https://carreiras.ifood.com.br/) tudo o que o iFood tem a te oferecer :)

## Requisitos

**Obrigatórios:**
- Experiência com Flutter
- Experiência com desenvolvimento mobile nativo

## Contratação

CLT

## Nossa empresa

iFood is the biggest and fastest growing FoodTech company in Latin America, operating in Brazil, Mexico and Colombia. We aim to make people live more convenient and joyful, by simplifying and disrupting the way they eat through applied technology. As a Android Software Engineer, you will design, code, test and operate developing and evolving applications that make it easy and part of our customers' universe, participating in the creation of APIs, integrating with the backend, and helping to prioritize evolution. taking into account the best value gains for the business.

We face huge scalability challenges, with more 30 million orders per month, 13 million users and over 100 thousand active restaurants.

## Como se candidatar

Por favor envie um email para glaydson.arantes@ifood.com.br com o link do seu LinkedIn - enviar no assunto: Vaga Flutter

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels

- Remoto
- CLT
- Pleno
- Sênior

**Comment by Romavic** [comment]
Vale remoto (Angola)...?...

**Comment by glaydsonarantesp** [comment]
> Vale remoto (Angola)...?...

Olá! Infelizmente não :/
