### ISSUE TITLE
[Jardim Paulista - SP] Analista de Segurança da Informação Sênior na @hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [flutterbr/vagas#126]
Responsabilidades:
• Planejar, desenvolver e revisar políticas e metodologias para gerenciamento dos controles de requerimentos regulatórios, diretrizes da empresa e melhores práticas segurança da informação;
• Monitorar métricas de Segurança da Informação e Privacidade de Dados e fornecer respostas proativas para os riscos atuais e futuros com base em diagnósticos;
• Conduzir a correção de riscos funcionais cruzados com as partes interessadas (TI, recursos humanos, áreas de negócio, etc.) e manter o painel de riscos e registrar os incidentes, incluindo geração de relatórios de progresso em relação aos KPIs;
• Planejar e desenvolver planos de ação corretivos e liderança de projetos para adequações necessárias;
• Entender e comunicar os objetivos do plano de Segurança da Informação internamente e para o cliente;
• Aplicar expertise e experiência para criar novas soluções de segurança da informação e Privacidade de Dados;
• Preparar e analisar relatórios periódicos (executivo e técnico);
• Implementar e manter Programa de LGPD e GDPR e Riscos de Segurança da Informação e Incidentes;
• Planejar, desenvolver e realizar sessões de treinamento e conscientização para todos os funcionários sobre os requisitos/melhorias de segurança da informação e privacidade de dados;
• Liderar o time de suporte de TI.

Requisitos e qualificações
Precisa ter experiência com:
• PDCA;
• 5W2h;
• Excel;
• PowerPoint;
• Ferramenta de dashboards;
• Gestão de indicadores; 
• ISO 27001;
• LGPD;
• Riscos.

Precisa ter:
• Capacidade para trabalho em equipe;
• Boa comunicação;
• Organização;
• Capacidade de negociação;
• Agilidade;
• Qualidade de entrega;
• Resiliência;
• Motivação;
• Perfil de liderança (será desenvolvido e terá equipe no futuro);
• Raciocínio Lógico.

Diferencial: 
Ter trabalhado em projeto da LGPD e implementado sistemas.

Alguns cursos possuem mais fit com a vaga: 
Especialização em Segurança da Informação ou cursos correlatos.

Salário: R$ 8.000,00 (regime de contratação poderá ser negociado)
Atuação no Jardim Paulista - ZS
Segunda a sexta-feira, das 09h às 18h - presencial

CVs via rh@hagloo.com

**Comment by irvine5k** [comment]
Oi, vi que sua vaga não possui nada relacionado a Flutter e estarei fechando-a.
