### ISSUE TITLE
[Remoto] Flutter Dev Mobile PLENO/SENIOR  na Space Sheep Games

### ISSUE THREAD

**Issue by NATALIAPASSOSG** [flutterbr/vagas#136]
## Descrição da vaga

- Desenvolver, dar manutenção e publicar jogos com potencial de alto desempenho no mercado;
- Garantir a estabilidade estrutural do projeto nas questões técnicas, intergração de SDKs e bibliotecas, geração de Build, ferramental e publicação em lojas;
- Contribuir nas decisões estratégicas sobre o desenvolvimento do jogo, junto a uma equipe de artistas, designers e gerentes de produto;
- Definir e trabalhar com as melhores tecnologias para o desenvolvimento;
- Se relacionar com um time de alta competência num ambiente colaborativo, descontraído e focado em entregar o melhor produto nas mão dos nossos milhões de usuários.

## Local

Remoto

## Benefícios

Cesta de benefícios flexíveis que você monta de acordo com seu perfil (Opções Ass. Médica, Ass. Odonto, VR, VA, Gympass)
Bônus e Participação nos lucros e resultados;
Auxílio Home Office.
Auxílio  creche.
Seguro de vida.

#### Diferenciais

Horário flexível.
Férias coletivas
Ambiente diverso: queremos que você seja você mesmo!
Happy hours de outro mundo [mesmo em modo home office #ficaquetemfesta]
Protagonismo de carreira
Liberdade para propor novas atividades, processos e metodologias

## Requisitos

**Obrigatórios:**

- Formação em Ciência da Computação, Engenharia de Computação, ou cursos correlatos;
- Domínio da linguagem C, C++, C# ou Java;
- Domínio de linguagem de script bash, Python ou Lua;
- Conhecimento de Design Orientado a Objetos;
- Inglês Avaçando

**Desejáveis:**

- Experiência com desenvolvimento com Unity 3D;
- Experiência com desenvolvimento com LOVE 2D;
- Experiência com controle de versão Git, SVN ou equivalente;

## Contratação

CLT ou PJ ( estamos abertos entender como prefere trabalhar)

## Nossa empresa

Fundada em 2020, a Space Sheep Games é uma desenvolvedora de jogos brasileira que atua no segmento mobile e seus jogos ultrapassam as fronteiras ao redor do mundo. Sob o comando do CEO René Retz, que empreende no setor de games e tecnologia há mais de dez anos, a Space Sheep Games conta com um time de 100 pessoas, focadas em desenvolver um negócio de alto desempenho, coragem para mudar as coisas e com a meta de sempre entregar o melhor para os jogadores ao redor do mundo.

Com a missão de divertir e conectar pessoas ao redor do mundo com jogos incríveis, a empresa chega com uma série de blockbusters internacionais em seu catálogo que somam mais de 93milhões de downloads ​– entre eles ​Bid Wars e ​Logic Pic. E, para 2021, promete novos lançamentos que vão proporcionar mais diversão de qualidade a um público que busca experiências memoráveis capazes de extrapolar os limites da tela do celular.

Navegue nessa Jornada!

## Como se candidatar

Por favor envie um email para natalia.passos@spacesheepgames.com com seu CV anexado - enviar no assunto: Vaga Dev Mobile

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- CLT
- Freela
- PJ
- Pleno
- Remoto
- Sênior

**Comment by irvine5k** [comment]
Oi, não consegui achar nenhuma menção ao Flutter na descrição da vaga, ela está realmente correta?

**Comment by NATALIAPASSOSG** [comment]
> Oi, não consegui achar nenhuma menção ao Flutter na descrição da vaga, ela está realmente correta?

Olá , irei tirar o anúncio pois coloquei no local errado peço desculpas.
