### ISSUE TITLE
[Remoto] Flutter Developer na Havan

### ISSUE THREAD

**Issue by BlackLeg15** [flutterbr/vagas#137]
## Descrição da vaga

Olá, tudo bem? A Fernanda, Tech Recruiter no Grupo Selecionar, está com uma SUPER oportunidade para Desenvolvedor Kotlin na MAIOR loja de departamentos do #BRASIL 🗽 Gostaria de saber mais sobre a oportunidade?

## Local

- Havan

## Requisitos

**Obrigatórios:**
- Domínio de Kotlin.
- Lógica de programação.
- Conhecimento POO (Programa orientada a objetos).
- Conhecimento em banco de dados SQL, mySQL.
- Experiência com integrações REST
- Conhecimento em base de dados SQL Lite.
- Conhecimento dos principais componentes do Jetpack.
- Experiência com Padrões de Material Design.
- Versionamento de código Git.
- Injeção de dependência.
- Conhecimento em testes unitários e de interface.
- Clean Code.
- Conhecimento em consumo de APIs JSON/REST.
- Conhecimento em alguma das arquiteturas Mobile (MVC, MVVM, MVP)

**Diferenciais:**
- SOLID
- Experiência em desenvolvimento Back-end
- Conhecimento em otimização de performance e segurança
- Domínio dos conceitos UX e UI
- Testes unitários
- Testes instrumentais
- Conhecimento em metodologias ágeis (Scrum/Kanban)

## Contratação

CLT

## Como se candidatar

Contatar a Fernanda dos Santos - Tech Recruiter
https://www.linkedin.com/in/fernanda-dos-santos-95a9b6216/

## Labels

- Remoto
- CLT

**Comment by irvine5k** [comment]
Oi, não vi nenhuma menção a Flutter ou Dart na descrição da vaga, está realmente correto?

Existem outros repositórios que podem se encaixar melhor com essa vaga.
