### ISSUE TITLE
[REMOTO] Flutter Developer Sr. na BossaBox 🤖

### ISSUE THREAD

**Issue by joaozanocelo** [flutterbr/vagas#145]
### BossaBox

- Somos um marketplace que conecta e faz a gestão do relacionamento entre grandes empresas que querem fazer produto e times de tech do Brasil. Estamos com 4 vagas abertas pra Dev. Flutter em um produto de uma rede de postos com mais de 30MM de usuários aqui no Brasil. 

### Algumas infos importantes:

- Disponibilidade de 6 horas diárias
- Remuneração de 15k/mês (O pagamento é feito quinzenalmente)
- Senioridade que buscamos: Sr.

### Mais sobre a Bossa

- Metodologia e relacionamento com clientes ficam por nossa conta para que vocês possam focar em código
- Remuneração quinzenal e segura, não atrelada a entrega ou horas, mas sim a performance
- Acesso à uma comunidade de profissionais e empresas de tecnologia
- Aprendizado contínuo por meio de treinamentos e conteúdos periódicos

Link da vaga:
https://hubs.li/H0VdYfk0

Valeu pessoal!

**Comment by enzodanjour** [comment]
Já foi fechado essa vaga, por favor @joaozanocelo fechar vaga
