### ISSUE TITLE
[REMOTO] Flutter Developer na KOBE APPS

### ISSUE THREAD

**Issue by julialbaldi** [flutterbr/vagas#147]
**FLUTTER DEVELOPER KOBE**
[https://kobe.gupy.io/jobs/1110614](url)

Nível de experiência: Pleno 

Modelo de contratação: CLT

**BENEFÍCIOS:**
- Your Way Holidays: 10 dias de recesso de final de ano sem desconto no tempo de férias
- Health Insurance: plano de saúde, odontológico e seguro de vida 100% cobertos e sem coparticipação
- Flexible Time: possibilidade de gerenciar sua agenda com autonomia (e claro, responsabilidade!) 
- Kober Remote Experience: cultura remote first com atividades de integração periódicas para Kobers 
- Kobe Growth: Plano de Desenvolvimento Individual (PDI) para cada Kober
- International Culture: cultura internacional com projetos e escritórios fora do Brasil
- The Right Tools: equipamento de alto nível para sua estrutura de trabalho

**ATIVIDADES:**
- Desenvolver aplicações em Flutter dando suporte a todo o ciclo de vida: concepção, design, teste, release e suporte a novas e existentes funcionalidades;
- Analisar, compreender e discutir os requisitos funcionais e técnicos, propondo a melhor abordagem para desenvolvimento e testes;
- Acompanhar entregas específicas com um espírito inovador, melhoria contínua e obsessão por superar as expectativas do cliente.

**SOBRE A KOBE:**

A Kobe é uma empresa jovem, cheia de criatividade e talento! Somos movidos por melhorar a vida das pessoas desafiando a forma como vivemos. Unimos pessoas apaixonadas por solucionar problemas usando Tecnologia, Design e empatia. Nosso estilo de trabalho é desenhado para que os Kobers possam construir a carreira dos seus sonhos, trabalhando juntos e unindo o melhor de dois mundos: um ambiente descontraído e colaborativo com altos desafios e responsabilidades.

**Comment by andremeireles** [comment]
> [https://kobe.gupy.io/jobs/1110614](https://github.com/flutterbr/vagas/issues/url)

Não sei porque mas, recebendo essa issue por email, o link está correto, mas no navegador está apontando para https://github.com/flutterbr/vagas/issues/url

Confere se está escrito assim: `[https://kobe.gupy.io/jobs/1110614](https://kobe.gupy.io/jobs/1110614)` resultado: [https://kobe.gupy.io/jobs/1110614](https://kobe.gupy.io/jobs/1110614)
