### ISSUE TITLE
[Remoto] Flutter Developer no @BANK

### ISSUE THREAD

**Issue by Edafopec** [flutterbr/vagas#160]
<!-- 
==================================================
Buscamos profissionais que sejam comprometidos com resultados, criativos nas resoluções de problemas, que vibram energia, que são movidos pela curiosidade, que sabem construir junto com outras pessoas e desfrutem do trabalho em equipe, que persistem e estão dispostos a superar os limites.
Buscamos tanto profissionais no nível pleno quanto JR e trainee.

Requisitos

conhecimento prévio em flutter
Conhecimento em desenvolvimento de aplicativos
Conhecimento em Banco de Dados
Ter cursado ou estar cursando superior relacionada a TI
Excelente lógica de programação
Colaborativo e com facilidade para trabalhar em equipe

Diferenciais

APIs REST
Experiência com metodologias Ágeis
Azure Devops e GitLab

Vaga flexível entre remoto e hibrido

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para envio do currículo : rodrigo@edafopec.com

site do projeto: www.arrobank.com.br

## Labels

- CLT
- trainee
- Júnior
- Pleno
- Remoto

**Comment by irvine5k** [comment]
Fechando pois não possui descrição.
