### ISSUE TITLE
[REMOTE] Flutter Developer na Kobe Global Software House

### ISSUE THREAD

**Issue by mariazepe** [flutterbr/vagas#166]
## Sobre o desafio 📱

Nessa oportunidade você fará parte do Time de Engenharia da Kobe e será crucial para o business, atuando em projetos inovadores e utilizando de tecnologias avançadas ao lado de um time altamente colaborativo.

## Local 🌍

Remoto

## Benefícios 🚀

- **Food Voucher:** R$25/dia
- **Your Way Holidays**: 10 dias de recesso de final de ano sem desconto tempo de férias (+-40 dias no total)
- **Health Insurance:** plano de saúde, odontológico e seguro de vida 100% coberto e sem coparticipação
- **Flexible Time:** possibilidade de gerenciar sua agenda com autonomia (e claro, responsabilidade!) 
- **Kober Remote Experience**: cultura remote first com atividades de integração periódicas para Kobers 
- **Kobe Growth:** Plano de Desenvolvimento Individual (PDI) para cada Kober
- **International Immersion**: cultura internacional com projetos e escritórios fora da BR
- **The Right Tools**: equipamento de alto nível para sua estrutura de trabalho

## Requisitos ☝️

**O desafio vai ser mais natural se você já tiver**
- Experiência de 3+ anos em desenvolvimento Mobile;
- Desenvolvido anteriormente projetos em Flutter;
- Experiência nas diferentes etapas do ciclo de desenvolvimento de um app.

**Desejáveis:**
-Experiência atuando com times SCRUM;
- Vivência em projetos desenvolvidos em Flutter de grande porte ou com impacto em um número expressivo de usuários.

## Contratação ⚖️

CLT

## Sobre a Kobe

Somos uma empresa que cria apps usando tecnologia, design e empatia. Ajudamos empresas a desenhar, construir e lançar produtos digitais. Alguns cases de sucesso são: Tok & Stok, Agibank, Warren, Decathlon & muitos outros!

Para mais info acesse: https://www.kobe.io/cases

## Curtiu? 💥

Só se candidatar através do link: https://kobe.gupy.io/jobs/1110614

Ou enviar um email para: maria.zepeda@kobe.io com o CV anexado.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👥 Pleno
- ⚖️ CLT

**Comment by andersonmendesdev** [comment]
Boa tarde, eu me candidatei nesta vaga a cerca de 20 dias e meu processo esta parado na etapa 1 desde então, é comum isso?

**Comment by mariazepe** [comment]
Boa tarde, @andersonmendesdev ! Para nós aparecia como se você tivesse desistido do processo há 7 dias. Confere essa info? Caso contrário, logo mais entraremos em contato :)

**Comment by andersonmendesdev** [comment]
> Boa tarde, @andersonmendesdev ! Para nós aparecia como se você tivesse desistido do processo há 7 dias. Confere essa info? Caso contrário, logo mais entraremos em contato :)

Estranho, não desisti da vaga, quando a gente desisti da vaga ela é removido do painel de candidaturas.
