### ISSUE TITLE
[São Paulo] Flutter Developer na Espresso Labs

### ISSUE THREAD

**Issue by espressolabs** [flutterbr/vagas#17]
## Descrição da vaga

**Sobre a Espresso Labs**
Somos uma software house dedicada a criar sistemas e aplicativos da mais alta qualidade para nossos clientes. Com um pouco mais de 2 anos de empresa já atendemos desde startups em ascensão até multinacionais como C&A e Unilever. Queremos aumentar o nosso time jovem e apaixonado por tecnologia para 40 pessoas até o ano que vem.

**Trabalho**
Temos clientes de uma grande variedade de setores, como automotivo, médico, esportivo, alimentício, entre outros. Dessa forma, sempre surgem novos desafios! Pela confiança dos clientes, geralmente escolhemos as tecnologias que cada um usará. Assim, você tem a possibilidade de moldar o nosso stack de tecnologias e processos das empresas. Atualmente utilizamos Ionic nos nossos aplicativos, mas nos planejamos para fazer a transição para o Flutter neste ano.

Não possuímos dress code e permitimos horários flexíveis para todos os colaboradores.

## Local

Nosso escritório atual fica na Rua Gomes de Carvalho, São Paulo - Vila Olímpia
Mas a partir de abril estamos na região de Pinheiros, perto do metrô Oscar Freire!

## Requisitos

**Obrigatórios:**
- Fundamentos básicos de Flutter
- 1 ano de experiência com desenvolvimento mobile ou frontend

**Desejáveis:**
- conhecimentos em Angular
- conhecimentos em Ionic

**Diferenciais:**
- projetos opensource

## Contratação

CLT ou PJ, a combinar

## Como se candidatar

Por favor envie seu CV em: https://espressolabs.com.br/equipe e vamos crescer juntos!

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: oi@espressolabs.com.br

## Labels

- CLT
- Estágio
- Júnior
- PJ
- Pleno

**Comment by gutosoares** [comment]
Tem opcão de remoto?

**Comment by espressolabs** [comment]
Olá Augusto! Infelizmente não conseguimos oferecer opção de remoto :/

**Comment by murilinhoPs** [comment]
Essa vaga pode ser pra estágio?

**Comment by espressolabs** [comment]
Olá @murilinhoPs, obrigado pelo interesse! Temos a possibilidade de estágio também
