### ISSUE TITLE
[São Caetano do Sul, SP] Flutter Developer na ViajaNet

### ISSUE THREAD

**Issue by RafaelMagalhaesN** [flutterbr/vagas#19]
## Descrição da vaga
Trabalhe no desenvolvimento do app da ViajaNet.

Venha inovar, criar e ajudar a ViajaNet a ter o melhor aplicativo de agência on-line do Brasil. Objetivo é desenvolver as novas funcionalidades, desde criar as telas até integrações com APIs da ViajaNet e SDKs de terceiros.

## Local

Escritório, São Caetano do Sul - Centro 

## Requisitos

**Obrigatórios:**
- Desenvolvimento mobile (nativo: iOS / Android ou hibrido: Flutter);
- Swift, Kotlin ou Dart;
- Git;
- Publicação de apps na PlayStore e/ou na AppStore.

**Desejáveis:**
- Experiência com a metodologia Kanban;
- Firebase;
- GitFlow;

**Diferenciais:**
- Projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Atenta ao movimento e crescimento do setor de travel online no mercado brasileiro, o ViajaNet é uma agência de viagens online que traz diferenciais no atendimento e nos serviços junto ao e-consumidor. Com mais de sete bilhões de tarifas aéreas à disposição do internauta, 100 mil hotéis listados no portal para pesquisa, 900 companhias aéreas, seguro e pacotes turísticos, a empresa conta com infraestrutura de ponta para o atendimento online ao consumidor. O ViajaNet é 100% nacional e aposta no mercado brasileiro, oferecendo ao consumidor a oportunidade de descobrir o mundo a um clique de distância. https://www.viajanet.com.br/

## Como se candidatar

Mande seu currículo para jhunger@viajanet.com.br

https://www.linkedin.com/feed/update/urn:li:activity:6638903588959600640/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

## Labels

- Alocado
- PJ
- Júnior
- Pleno
- Sênior

**Comment by WilliamCunhaCardoso** [comment]
Há possibilidade de remoto?

**Comment by RafaelMagalhaesN** [comment]
Opa William.
Infelizmente não.

**Comment by WilliamCunhaCardoso** [comment]
> Opa William.
> Infelizmente não.

Tranquilo. Obrigado pelo retorno
