### ISSUE TITLE
[São Paulo (Freela)] Flutter Developer na MELIORA CONSULTORIA

### ISSUE THREAD

**Issue by anderson-zanni** [flutterbr/vagas#21]
Projeto mobile meliorApp em Flutter.

Part-time Remoto (ou Escritório, São Paulo - Vila Leopoldina - apenas reuniões de alinhamento)

**Requisitos obrigatórios:**
Desenvolvimento mobile (Flutter);
Dart;
Git;
OneSignal;
Publicação de apps na PlayStore e/ou na AppStore (conhecimento básico).

**Contratação**
Valor pago por hora de desenvolvimento apontadas no final do período (PJ)

**Nossa empresa**
Consultoria especializada em implantação, suporte e desenvolvimento em Protheus (Totvs) com App destinado a integrações de processos.

**Como se candidatar**
Por favor envie um email para anderson.zanni@meliora.com.br com seu CV anexado - enviar no assunto: Vaga Flutter ou contato pelo Whats: (11) 99435-1222

**Labels**
- Freela
- Remoto
- Sênior

**Comment by Daniray2008** [comment]
Ola, gostaria de saber se tem alguma oportunidade para junior?
