### ISSUE TITLE
[Curitiba/PR] Flutter Developer na Snowman Labs

### ISSUE THREAD

**Issue by denisviana** [flutterbr/vagas#27]
## Local

Escritório, Curitiba/PR - Rebouças

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- Vale Refeição
- Vale Alimentação
- Vale Transporte 

#### Diferenciais

- Horário flexível 
- Dia da fruta
- Inglês
- Ping-pong/Fliperama

## Requisitos

**Obrigatórios:**
- 7 anos de experiência.
- Aptidão em liderança de equipes.
- Domínio em diferentes Arquiteturas de Software.
- Proficiência em Dart.
- Domínio das API’s do Android e serviços do Google e/ou Kits de desenvolvimento para
- iOS.
- Experiência com Clean Architecture.
- Entender padrões de programação reativa.
- Entender padrões de programação assíncrona.
- Experiência com SQLite no Android e iOS.
- Experiência com refatoração de software legado.
- Experiência com aplicações complexas.
- Domíno de Git.
- Vasto conhecimento e domínio REST.
- Capacidade de arquitetar API’s no padrão OpenAPI.
- Domínio de Testes unitários e de integração.
- Experiência com Scrum.
- Experiência com publicações na Play Store e/ou Google Play.
- Experiência com publicação para testes usando Fabric e/ou TestFlight.
- Ter pelo menos um App desenvolvido por você publicado na Play Store e/ou App Store.
- Inglês: escrita e conversação intermediários.

**Desejáveis:**
- Experiência com CI/CD.
- Experiência com GraphQL ou JSON:API. • Experiência com BDD.
- Inglês avançado.

**Oportunidade de Aprendizado:**
- IoT.
- AR e VR.
- Machine Learning.
- Blockchain.

## Contratação

CLT a combinar

## Nossa empresa

Na Snow você irá promover a Revolução Digital de muitas empresas e negócios, trabalhando em ambiente descontraído e flexível. Junto a profissionais incríveis, capazes de feitos extraordinários, irá encontrar desafios e descobrir como resolve-los, por vezes de formas inesperadas e inovadoras.
Nossas salas têm nomes de montanhas, pois representam as grandes escaladas que fazemos diariamente rumo aos nossos objetivos. E é nesse ritmo de escalada que nos preparamos para uma nova fase, a promoção da Evolução Digital de nossos clientes oferecendo novas formas de levar seu negócio ao próximo nível da tecnologia atual.
Você está preparado?

## Como se candidatar

Por favor envie um email para rh@snowmanlabs.com com seu CV anexado - enviar no assunto: Vaga Flutter

## Labels

- CLT
- Sênior

**Comment by jeaanlucas** [comment]
Fiz a minha candidatura pelo e-mail. Vocês não disponibilizam remoto?
