### ISSUE TITLE
[São Paulo] Flutter Developer Pleno - BeeTech

### ISSUE THREAD

**Issue by zeucxb** [flutterbr/vagas#36]
### Sobre a BeeTech 🌏
Nossa missão é possibilitar que as pessoas tenham uma vida global, com serviços financeiros que não são limitados a fronteiras. Acreditamos que todos devem ter a oportunidade de fazer o melhor uso do seu dinheiro, não importa onde estejam. Juntos, estamos criando um mundo sem fronteiras financeiras.

### O que você vai fazer aqui na BeeTech 🚀 

- Participar ativamente do desenvolvimento e planejamento dos apps da BeeTech
- Desenvolver layouts responsivos (para diversos tipos de celulares)
- Trabalhar no processo de qualidade do app (testes, esteira, deploy)
- Desenvolver apps de qualidade “premium” com base em dados e foco no usuário

### E o que você precisa ter 📚 

- Experiência com Flutter
- Experiência com gerenciamento de estado (mobx, bloc, getx e etc )
- Experiência em processos ageis
- Já ter testado alguma feature (unitário/widget)
- Experiência com ferramentas de gerenciamento de projetos (Jira, Clubhouse, Trello e etc)

### E o que seria legal se você tivesse 👍 

- Experiência com esteiras de deploy
- Conhecimento de fastlane
- Experiência com desenvolvimento nativo
- Experiência com testes (unitários, widget)
- Experiência com tracking
- Conhecer feature toggle
- Conhecimento de Firebase

### Como é trabalhar na Bee 🐝
Aqui na BeeTech somos como uma colmeia: trabalhamos juntos e ajudando uns aos outros, sempre focados em alcançar os melhores resultados. Nosso ambiente é acolhedor e a diversidade é respeitada. Aqui você pode meditar ou tirar um cochilo na hora no almoço, sabia? As tardes de terça e quinta são acompanhadas por bolos e frutas, para que você dê uma pausa no trabalho e adoce a rotina. Além disso, temos muitas ações que visam promover a integração de nosso time, olha só:

#IntegraBee: Um evento de integração que reúne todos da empresa, trazendo a história inspiradora de um dos Bees e seguido por comes e bebes (muitos bebes);

#De People pra Bee: Iniciativa mensal que traz temas sobre diversos assuntos que os próprios Bees pedem, como por exemplo  CNV, Oratória, e etc; Tudo isso para fortalecer ainda mais o time como um todo;

#Inside the hive: Evento mensal onde o nosso CEO compartilha os resultados da empresa e os desafios futuros da Hive. É o momento onde todos têm uma visão geral do que anda acontecendo em cada área.
Acreditamos que conhecimento é para ser compartilhado, por isso gostamos de abrir nossas portas para que a comunidade agregue com suas experiências através de Meetups e Tech Talks.

### Onde fica nosso escritório 📌

Estamos na Faria Lima, pertinho do metrô! ;) 

### Como geralmente funciona o nosso processo seletivo 🔍

Inscrição
Entrevista com o RH
Entrevistas com o time/gestor 
Oferta 

### O que temos de benefícios? 💙💚

Salário Competitivo 
Assistência Médica Allianz; 
 
Curtiu? Se candidate na nossa vaga e venha ser feliz! Caso você não se identifique com essa vaga, compartilhe com os seus amigos.

[Candidate-se](https://jobs.kenoby.com/beetech/job/flutter-developer-pl/5f3c1ed9b3871d432c6ca74a)

**Comment by zeucxb** [comment]
Vaga é contratação **PJ**, **Fulltime** e pode ser **Remoto** ou **Presencial**.

**Comment by Octaniel** [comment]
Estou interessado, sou especialista em Spring boot, angular, Ionic, Flutter e Arqueduct
