### ISSUE TITLE
[São Paulo] Flutter Developer na Augazo

### ISSUE THREAD

**Issue by Vjagosich** [flutterbr/vagas#5]
Desenvolvimento de aplicação Mobile em Flutter e Dart.
Hoje a equipe é pequena 2 desenvolvedores Junior no Framework e linguagem e precisamos de mais ajuda.
O layout e design já existente.
Back-end já existente.
Poderá ser contrato por demanda ou fixo mensal;
Projeto para 2 meses;
Execução remoto com reuniões diárias e repositório geral no bitbucket;

#### Diferenciais
Estamos aprendendo e temos abertura para receber pessoas que estão no mesmo nível de desenvolvimento em Flutter que a gente; O importante é usar e colocar em prática;

## Requisitos (mas precisamos que os candidados conheçam outras plataformas para saber o que estamos falando no dia dia e buscar referencias para o mesmo processo em Flutter);
- Experiência com desenvolvimento mobile nativo em outros frameworks - React, Angular, Ionic;
- Experiência em desenvolvimento Front-end em equipe e de forma remota - Git;

## Contratação

PJ a combinar

## Nossa empresa

A Augazo é uma empresa de RH que quer ser diferente no mercado colocando em produção uma plataforma para desenvolvimento pessoal.
Temos uma equipe reduzida de TI, desenvolvedores em que atualmente por decisão de crescimento estamos buscando novos colaboradores.

## Como se candidatar

Por favor envie um email para valter@iwho.io com seu CV anexado - enviar no assunto: Vaga Flutter

**Comment by MatheusNCarvalho** [comment]
Bom dia, tudo bem ?
Gostaria de saber se a vaga ainda está disponível.

**Comment by kevenny03** [comment]
Ainda há vagas disponíveis?
