### ISSUE TITLE
[REMOTO] Flutter Developer na GPS SAT

### ISSUE THREAD

**Issue by gpssat** [flutterbr/vagas#55]
## Descrição da vaga

Atuar no desenvolvimento com Flutter em projetos desafiadores.
Oportunidade de atuar em projetos utilizando metodologia ágil.

## Local

Remoto 

## Requisitos

**Obrigatórios:**

- Conhecimento de Dart;
- Bom conhecimento sobre a plataforma Flutter;
- Frameworks e bibliotecas;
- Versionamento de código usando ferramenta Git;
- Facilidade de comunicação e proatividade;

**Desejáveis:**

- Laravel
- Postgresql

## Contratação

PJ a combinar

## Nossa empresa

Estamos há 10 anos atuando no desenvolvimento de soluções para gestão e monitoramento de máquinas e veículos.

## Como se candidatar

Por favor envie um email para rh@gpssat.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Flutter

**Comment by caciolucas** [comment]
Bom dia, qual a carga horária da vaga?

**Comment by Jaofranca** [comment]
Como atualmente estou na faculdade seria melhor uma carga horária reduzida, 6 horas seria perfeito

________________________________
De: Cácio Lucas <notifications@github.com>
Enviado: domingo, 29 de novembro de 2020 08:02
Para: flutterbr/vagas <vagas@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [flutterbr/vagas] [REMOTO] Flutter Developer na GPS SAT (#55)


Bom dia, qual a carga horária da vaga?

**Comment by gpssat** [comment]
> Bom dia, qual a carga horária da vaga?

Boa tarde.

40h semanais.
