### ISSUE TITLE
[REMOTO / RECIFE] FLUTTER DEVELOPER | BHAVE

### ISSUE THREAD

**Issue by thiagolives** [flutterbr/vagas#66]
## Descrição da vaga

Projeto Mobile em Flutter

## Local

- Remoto 
- A empresa possui escritório no Porto Digital em Recife 

## Requisitos

- Conhecimento e experiência em Flutter
- Boas práticas de programação (Clean Code)
- GIT
- Boa comunicação interpessoal
- Ter um computador
- Gostar muito de aprender

Pode te ajudar muito:

- Experiência com Ionic
- Conhecimento em Firebase 
- Noções em Banco de dados 
- Algum conhecimento em Python 
- Experiência com testes automatizados

## Contratação

PJ a combinar

## Nossa empresa

Somos bHave. Trabalhamos com Inovação para Terapia dedicada ao autismo e queremos você em nosso time de tecnologia.

## Nossa Proposta

Contratação Imediata
Home Office
Horário flexível (4 ou 8 horas)
Nível de experiência: Júnior, Pleno e Sênior.
Remuneração: 2k a 5k

## Como se candidatar

Por favor envie um email para bhave.vagas@gmail.com com seu CV anexado - enviar no assunto: Vaga Flutter

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- PJ
- Remoto
- Júnior
- Pleno
- Sênior

**Comment by feliper2002** [comment]
Aceita se enviar apenas GitHub e Portfólio Web?

**Comment by thiagolives** [comment]
Bom dia, Felipe.

Envia o que você tiver que analizaremos.
Em 9 de fev de 2021 01:25 -0300, Felipe Ribeiro <notifications@github.com>, escreveu:
